### ISSUE TITLE
Find an API to check internet speed

### ISSUE THREAD

**Issue by devcer** [firefox-addons/speed-checker#2]
Find a javascript API to check internet  speed and log the internet speed on browser_action button click.

@tsl143, @iamVP7 and I would be happy to mentor if someone is interested to find a reliable API for us. :)

**Comment by g33kidd** [comment]
I was able to find https://github.com/ddsol/speedtest.net/blob/master/index.js which seems like a pretty good option. It uses the speedtest.net api for gathering the data.

**Comment by azharakbar** [comment]
I have added the code for checking the internet speed by iusing an image object

Raised a pull request

**Comment by azharakbar** [comment]
@viswanathamsantosh I have just added the speed-test tool ... jst look at it .. :)

**Comment by devcer** [comment]
@azharakbar thanks for submitting the PR, but PR a user will have to download the image in your PR to check his internet speed so we are looking for a REST API which you could use to check the internet speed. If you are interested to work on this I can assign this issue to you. There is another PR opened with a list of API's which could help you as a reference. what do you think?

**Comment by azharakbar** [comment]
Yes, I am ready .. pls assign it to me ... 
I have seen the PR which had the list of APIs .. but the problem with them is ... 
They are not free
They give results for specific regions only .. example ... only the US
Some of them uses backend javascript and php for getting it done ... which cant be used for the firefox addon project since we can use only the frontend js and API calls only ... 
Another method will be like to host a dummy server only having the backend code for speed-check and request that server for speed check reponse through api calls ... 
These are my findings...
@viswanathamsantosh

**Comment by devcer** [comment]
Ummm! In that case I will merge your PR after I test it tonight(since it requires only 5 mb to download). Thanks @azharakbar :)

**Comment by devcer** [comment]
Thank you @azharakbar ! The PR wasn't giving us accurate result all the time but until we find a better solution, we will use your logic. Happy hacktoberfest. :)

**Comment by azharakbar** [comment]
Thank You very much @viswanathamsantosh .... :)
